version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database_name
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=password
  web:
    build: ./my_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./my_site:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
