version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database_name
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=password
    networks:
      - backend

  web:
    build: ./my_site
    command: gunicorn -b:8000 my_site.wsgi
    volumes:
      - ./my_site:/code
      - static_files:/code/static/
    expose:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT:-81}:${NGINX_PORT:-81}
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - static_files:/code/static/
    networks:
      - backend
    depends_on:
      - web
    environment:
      - NGINX_PORT=${NGINX_PORT:-81}

  next_app:
    build:
      context: ./next_app
      dockerfile: dev.Dockerfile
    volumes:
      - ./next_app/src:/app/src
      - ./next_app/public:/app/public
    expose:
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - backend
      - frontend
    env_file:
      - ./next_app/.env.local

volumes:
  static_files:

networks:
  backend:
  frontend:
